[package]
authors = ["patract labs <https://github.com/patractlabs>"]
edition = "2018"
name = "metis_erc721_receiver"
version = "0.1.0"

[dependencies]
ink_env = {version = "3.0.0-rc5", git = "https://github.com/paritytech/ink", default-features = false}
ink_lang = {version = "3.0.0-rc5", git = "https://github.com/paritytech/ink", default-features = false}
ink_metadata = {version = "3.0.0-rc5", git = "https://github.com/paritytech/ink", default-features = false, features = ["derive"], optional = true}
ink_prelude = {version = "3.0.0-rc5", git = "https://github.com/paritytech/ink", default-features = false}
ink_primitives = {version = "3.0.0-rc5", git = "https://github.com/paritytech/ink", default-features = false}
ink_storage = {version = "3.0.0-rc5", git = "https://github.com/paritytech/ink", default-features = false}

hex = {version = "0.4", default-features = false}
num-traits = {version = "0.2", default-features = false, features = ["i128"]}
scale = {package = "parity-scale-codec", version = "2.1", default-features = false, features = ["derive"]}
scale-info = {version = "0.6", default-features = false, features = ["derive"]}

metis_erc721_types = {path = "../types", default-features = false}
metis_lang = {path = "../../../../lang/", default-features = false}

[features]
default = ["std"]
ink-as-dependency = []
std = [
  "ink_metadata/std",
  "ink_storage/std",
  "ink_prelude/std",
  "ink_primitives/std",
  "ink_env/std",
  "ink_lang/std",
  "scale/std",
  "scale-info/std",
  "metis_lang/std",
  "metis_erc721_types/std",
]
