name: Megaclite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.head_commit.message), 'ci(skip)')"
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v1
      - name: Set nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: wasm32-unknown-unknown
      - name: Cache Rust Outputs
        uses: actions/cache@v1
        env:
          cache-name: rust-cache
        with:
          path: ./target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*/Cargo.lock') }}
      - name: Pre
        run: cargo install cargo-contract
      - name: Build
        run: cd groth16 && cargo +nightly contract build --verbose
          
